Vagrant.configure(2) do |config|

	# Set some variables
  etcHosts=""
  common = <<-SHELL
  sudo apt update -qq 2>&1 >/dev/null
  sudo apt install -y -qq git vim tree net-tools telnet 2>&1 >/dev/null
  #sudo apt install -y -qq git vim tree net-tools telnet git python3-pip sshpass nfs-common 2>&1 >/dev/null
  #curl -fsSL https://get.docker.com -o get-docker.sh 2>&1
  #sudo sh get-docker.sh 2>&1 >/dev/null
  #sudo usermod -aG docker vagrant
  #sudo service docker start
  sudo echo "autocmd filetype yaml setlocal ai ts=2 sw=2 et" > /home/vagrant/.vimrc
  sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
  sudo systemctl restart sshd
  SHELL

	# set vagrant image
	config.vm.box = "ubuntu/focal64"
	config.vm.box_url = "ubuntu/focal64"

	# set servers list and their parameters
	NODES = [
  	{ :hostname => "vag1", :ip => "192.168.15.20", :cpus => 1, :mem => 1024 },
  	{ :hostname => "vag2", :ip => "192.168.15.21", :cpus => 1, :mem => 1024 },
  	{ :hostname => "vag3", :ip => "192.168.15.22", :cpus => 1, :mem => 1024 },
  	{ :hostname => "vag4", :ip => "192.168.15.23", :cpus => 1, :mem => 1024 },
  	{ :hostname => "vag5", :ip => "192.168.15.24", :cpus => 1, :mem => 1024 },
  	{ :hostname => "vag6", :ip => "192.168.15.25", :cpus => 1, :mem => 1024 },
  	{ :hostname => "vag7", :ip => "192.168.15.26", :cpus => 1, :mem => 1024 }
	]

	# define /etc/hosts for all servers
  NODES.each do |node|
   	etcHosts += "echo '" + node[:ip] + "   " + node[:hostname] + "' >> /etc/hosts" + "\n"
  end #end NODES

	# run installation
  NODES.each do |node|
    config.vm.define node[:hostname] do |cfg|
			cfg.vm.hostname = node[:hostname]
      cfg.vm.network "private_network", ip: node[:ip]
      cfg.vm.provider "virtualbox" do |v|
				v.customize [ "modifyvm", :id, "--cpus", node[:cpus] ]
        v.customize [ "modifyvm", :id, "--memory", node[:mem] ]
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        v.customize ["modifyvm", :id, "--name", node[:hostname] ]
      end #end provider
			
			#for all
      cfg.vm.provision :shell, :inline => etcHosts
			cfg.vm.provision :shell, :inline => common
    end # end config
  end # end nodes

      config.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/playbook.yml"
        #ansible.inventory_path = "ansible/inventory.yml"
        ansible.groups = {
          "group1" => ["vag1"],
          "group2" => ["vag2"],
          "group3" => ["vag[3:5]"],
          "all_groups:children" => ["group1", "group2"],
          "group1:vars" => {"myvar" => "grp1"},
          "group2:vars" => {"myvar" => "grp2"},
          "group3:vars" => {"myvar" => "grp2"},
          "all_groups:vars" => {"myvar" => "all"}
          }
      end


end 


